/// The high-protein recipe library.
///
/// 100 recipes: 20 breakfasts, 30 lunches, 50 dinners. Written to three rules:
///
///  1. **Protein first.** Every dinner clears ~45g and every lunch ~40g in a
///     single base portion, which is well above the envelope floor. This is the
///     one thing the library is really for.
///  2. **Every dinner contains meat**, and most lunches do. Fish, seafood, eggs
///     and dairy carry the variety instead of replacing it — including in dinners,
///     where chorizo-and-prawn or bacon-wrapped-cod get seafood onto the plate
///     without breaking the rule.
///  3. **Ingredients repeat on purpose.** A library of 100 unrelated dishes gives
///     the optimiser no overlap to find, and overlap is the entire mechanism by
///     which the shop gets cheaper (spec §8.4).
///
/// Quantities are for ONE base portion, at a scale factor of 1, and are sized at
/// roughly the meal's calorie envelope so the numbers read true before scaling.
/// Meat and the main carbohydrate are marked scalable — they are what a person
/// actually adjusts — while aromatics, oil and seasoning stay fixed.
///
/// Weights are as bought: raw for meat and fish, dry for grains and pulses,
/// drained for tins.

export type Line = {
  /** Ingredient name, exactly as seeded. */
  n: string;
  /** Grams for one base portion. */
  g: number;
  /** Scalable range, if the amount is one a person would actually adjust. */
  scale?: [number, number];
  note?: string;
};

export type RecipeSeed = {
  name: string;
  mealType: "breakfast" | "lunch" | "dinner" | "snack";
  prepMinutes: number;
  batchFriendly?: boolean;
  leftoversFreeze?: boolean;
  keepsDays?: number;
  method: string;
  lines: Line[];
};

export const HIGH_PROTEIN_RECIPES: RecipeSeed[] = [
  /* ══ BREAKFASTS (20) ══════════════════════════════════════════════════════ */
  {
    name: "Skyr with whey, berries and almonds",
    mealType: "breakfast",
    prepMinutes: 3,
    keepsDays: 1,
    method: "1. Stir the whey through the skyr until smooth.\n2. Top with berries, oats and almonds.",
    lines: [
      { n: "Skyr (0% fat)", g: 250, scale: [150, 350] },
      { n: "Whey protein powder", g: 20, scale: [10, 35] },
      { n: "Frozen berries", g: 80 },
      { n: "Rolled oats", g: 20, scale: [0, 50] },
      { n: "Almonds", g: 15 },
    ],
  },
  {
    name: "Smoked salmon and scrambled eggs on sourdough",
    mealType: "breakfast",
    prepMinutes: 10,
    keepsDays: 1,
    method: "1. Toast the sourdough.\n2. Scramble the eggs slowly with the butter.\n3. Drape the salmon over, plenty of black pepper.",
    lines: [
      { n: "Eggs", g: 145, scale: [87, 232] },
      { n: "Smoked salmon", g: 60, scale: [35, 100] },
      { n: "Sourdough bread", g: 70, scale: [30, 120] },
      { n: "Butter", g: 5 },
      { n: "Black pepper", g: 1 },
    ],
  },
  {
    name: "Cottage cheese and tomato on sourdough",
    mealType: "breakfast",
    prepMinutes: 5,
    keepsDays: 1,
    method: "1. Toast the sourdough.\n2. Spread the cottage cheese thickly.\n3. Top with sliced tomato, pumpkin seeds and pepper.",
    lines: [
      { n: "Cottage cheese", g: 200, scale: [140, 300] },
      { n: "Sourdough bread", g: 80, scale: [50, 130] },
      { n: "Tomatoes", g: 100 },
      { n: "Pumpkin seeds", g: 15 },
      { n: "Black pepper", g: 1 },
    ],
  },
  {
    name: "Protein pancakes with quark and raspberries",
    mealType: "breakfast",
    prepMinutes: 12,
    keepsDays: 1,
    method: "1. Blitz oats, egg whites and whey to a batter.\n2. Fry in small pancakes, 2 min a side.\n3. Stack with quark and raspberries.",
    lines: [
      { n: "Rolled oats", g: 50, scale: [35, 80] },
      { n: "Egg whites", g: 120, scale: [80, 200] },
      { n: "Whey protein powder", g: 25, scale: [15, 35] },
      { n: "Quark", g: 100 },
      { n: "Raspberries", g: 80 },
    ],
  },
  {
    name: "Bacon, egg and spinach muffin",
    mealType: "breakfast",
    prepMinutes: 10,
    keepsDays: 1,
    method: "1. Grill the bacon and toast the muffin.\n2. Fry the egg, wilt the spinach in the same pan.\n3. Build, with the cheddar going on hot.",
    lines: [
      { n: "English muffins", g: 67, scale: [34, 100] },
      { n: "Bacon medallions", g: 60, scale: [30, 100] },
      { n: "Eggs", g: 116, scale: [58, 174] },
      { n: "Spinach", g: 40 },
      { n: "Cheddar", g: 15 },
    ],
  },
  {
    name: "Greek yoghurt, chia and mango pot",
    mealType: "breakfast",
    prepMinutes: 5,
    batchFriendly: true,
    keepsDays: 3,
    method: "1. Stir the whey and chia into the yoghurt.\n2. Leave 10 min to thicken.\n3. Top with mango, walnuts and honey.",
    lines: [
      { n: "Greek yoghurt (0% fat)", g: 250, scale: [150, 350] },
      { n: "Whey protein powder", g: 15, scale: [10, 30] },
      { n: "Chia seeds", g: 15 },
      { n: "Mango", g: 120 },
      { n: "Walnuts", g: 10 },
      { n: "Honey", g: 10 },
    ],
  },
  {
    name: "Three-egg omelette with ham and cheddar",
    mealType: "breakfast",
    prepMinutes: 10,
    keepsDays: 1,
    method: "1. Fry the mushrooms hard until browned.\n2. Pour over the beaten eggs, add ham.\n3. Scatter cheddar, fold, rest a minute.",
    lines: [
      { n: "Eggs", g: 174, scale: [87, 232] },
      { n: "Sliced ham", g: 60, scale: [30, 100] },
      { n: "Cheddar", g: 30 },
      { n: "Mushrooms", g: 60 },
      { n: "Olive oil", g: 5 },
    ],
  },
  {
    name: "Overnight oats with whey and peanut butter",
    mealType: "breakfast",
    prepMinutes: 5,
    batchFriendly: true,
    keepsDays: 3,
    method: "1. Mix oats, milk and whey.\n2. Leave overnight.\n3. Swirl through peanut butter and sliced banana.",
    lines: [
      { n: "Rolled oats", g: 55, scale: [28, 85] },
      { n: "Semi-skimmed milk", g: 180, scale: [100, 260] },
      { n: "Whey protein powder", g: 25, scale: [12, 35] },
      { n: "Peanut butter", g: 15 },
      { n: "Banana", g: 60 },
    ],
  },
  {
    name: "Smoked mackerel and poached eggs on sourdough",
    mealType: "breakfast",
    prepMinutes: 10,
    keepsDays: 1,
    method: "1. Poach the eggs.\n2. Toast the sourdough.\n3. Flake the mackerel over, add rocket and lemon.",
    lines: [
      { n: "Smoked mackerel", g: 70, scale: [50, 110] },
      { n: "Eggs", g: 116, scale: [58, 174] },
      { n: "Sourdough bread", g: 55, scale: [30, 110] },
      { n: "Rocket", g: 20 },
      { n: "Lemon", g: 10 },
    ],
  },
  {
    name: "Shakshuka with feta and chickpeas",
    mealType: "breakfast",
    prepMinutes: 20,
    keepsDays: 2,
    method: "1. Soften onion and pepper, add cumin and paprika.\n2. Add tomatoes and chickpeas, simmer 10 min.\n3. Crack in the eggs, cover, cook 6 min. Crumble over feta.",
    lines: [
      { n: "Eggs", g: 145, scale: [87, 232] },
      { n: "Chopped tomatoes", g: 200, scale: [120, 260] },
      { n: "Chickpeas", g: 80, scale: [40, 130] },
      { n: "Feta", g: 40, scale: [20, 60] },
      { n: "Red pepper", g: 70 },
      { n: "Onion", g: 50 },
      { n: "Olive oil", g: 6 },
      { n: "Cumin", g: 2 },
      { n: "Smoked paprika", g: 2 },
    ],
  },
  {
    name: "Quark and berry protein bowl",
    mealType: "breakfast",
    prepMinutes: 4,
    keepsDays: 1,
    method: "1. Beat the whey into the quark.\n2. Fold through oats.\n3. Top with berries, pumpkin seeds and honey.",
    lines: [
      { n: "Quark", g: 250, scale: [150, 350] },
      { n: "Whey protein powder", g: 15, scale: [10, 30] },
      { n: "Frozen berries", g: 100 },
      { n: "Rolled oats", g: 25, scale: [0, 50] },
      { n: "Pumpkin seeds", g: 15 },
      { n: "Honey", g: 8 },
    ],
  },
  {
    name: "Chicken sausage and egg breakfast wrap",
    mealType: "breakfast",
    prepMinutes: 12,
    keepsDays: 1,
    method: "1. Grill the sausages, slice.\n2. Scramble the eggs, wilt spinach through.\n3. Fill the wrap, add sriracha, roll tight.",
    lines: [
      { n: "Chicken sausages", g: 100, scale: [50, 150] },
      { n: "Eggs", g: 116, scale: [58, 174] },
      { n: "Tortilla wraps", g: 62 },
      { n: "Spinach", g: 30 },
      { n: "Sriracha", g: 10 },
    ],
  },
  {
    name: "Tofu scramble with turmeric and spinach",
    mealType: "breakfast",
    prepMinutes: 12,
    keepsDays: 1,
    method: "1. Crumble the tofu into hot oil, fry until the edges catch.\n2. Add turmeric and season hard.\n3. Wilt spinach through, serve on toast with tomatoes.",
    lines: [
      { n: "Tofu (firm)", g: 200, scale: [120, 280] },
      { n: "Wholemeal bread", g: 80, scale: [40, 120] },
      { n: "Spinach", g: 60 },
      { n: "Tomatoes", g: 80 },
      { n: "Olive oil", g: 8 },
      { n: "Turmeric", g: 2 },
    ],
  },
  {
    name: "Cottage cheese pancakes with blueberries",
    mealType: "breakfast",
    prepMinutes: 12,
    keepsDays: 1,
    method: "1. Blitz cottage cheese, oats and eggs.\n2. Fry in small rounds, 2 min a side.\n3. Top with blueberries and maple syrup.",
    lines: [
      { n: "Cottage cheese", g: 150, scale: [100, 220] },
      { n: "Rolled oats", g: 45, scale: [30, 70] },
      { n: "Eggs", g: 100, scale: [58, 174] },
      { n: "Blueberries", g: 80 },
      { n: "Maple syrup", g: 10 },
    ],
  },
  {
    name: "Smoked salmon and cream cheese bagel",
    mealType: "breakfast",
    prepMinutes: 5,
    keepsDays: 1,
    method: "1. Toast the bagel.\n2. Spread with cream cheese.\n3. Layer salmon, cucumber and capers.",
    lines: [
      { n: "Bagels", g: 85, scale: [55, 130] },
      { n: "Smoked salmon", g: 90, scale: [60, 130] },
      { n: "Light cream cheese", g: 40 },
      { n: "Cucumber", g: 40 },
      { n: "Capers", g: 5 },
    ],
  },
  {
    name: "Egg white and mushroom frittata",
    mealType: "breakfast",
    prepMinutes: 20,
    batchFriendly: true,
    keepsDays: 3,
    method: "1. Fry mushrooms and sliced potato until browned.\n2. Pour over egg whites beaten with the whole egg.\n3. Scatter parmesan and spinach, finish under the grill.",
    lines: [
      { n: "Egg whites", g: 250, scale: [150, 350] },
      { n: "Eggs", g: 58 },
      { n: "Mushrooms", g: 100 },
      { n: "New potatoes", g: 100, scale: [60, 160] },
      { n: "Parmesan", g: 25, scale: [12, 35] },
      { n: "Spinach", g: 50 },
      { n: "Olive oil", g: 6 },
    ],
  },
  {
    name: "Peanut butter and banana protein oats",
    mealType: "breakfast",
    prepMinutes: 8,
    keepsDays: 1,
    method: "1. Cook the oats in the milk.\n2. Beat in the whey off the heat.\n3. Top with banana and peanut butter.",
    lines: [
      { n: "Rolled oats", g: 50, scale: [28, 80] },
      { n: "Semi-skimmed milk", g: 200, scale: [110, 300] },
      { n: "Whey protein powder", g: 25, scale: [12, 35] },
      { n: "Peanut butter", g: 12 },
      { n: "Banana", g: 80 },
    ],
  },
  {
    name: "Greek yoghurt with oats, walnuts and honey",
    mealType: "breakfast",
    prepMinutes: 4,
    keepsDays: 1,
    method: "1. Stir the whey through the yoghurt.\n2. Fold in oats.\n3. Top with strawberries, walnuts and honey.",
    lines: [
      { n: "Greek yoghurt (0% fat)", g: 250, scale: [150, 350] },
      { n: "Whey protein powder", g: 15, scale: [8, 30] },
      { n: "Rolled oats", g: 40, scale: [20, 65] },
      { n: "Strawberries", g: 80 },
      { n: "Walnuts", g: 15 },
      { n: "Honey", g: 12 },
    ],
  },
  {
    name: "Turkey and potato breakfast hash",
    mealType: "breakfast",
    prepMinutes: 20,
    keepsDays: 2,
    method: "1. Fry diced potato until crisp.\n2. Add turkey mince, pepper and onion, brown hard.\n3. Fry an egg on top, add sliced avocado.",
    lines: [
      { n: "Turkey mince (5% fat)", g: 120, scale: [70, 180] },
      { n: "New potatoes", g: 150, scale: [85, 240] },
      { n: "Eggs", g: 58 },
      { n: "Red pepper", g: 60 },
      { n: "Onion", g: 40 },
      { n: "Avocado", g: 30 },
      { n: "Olive oil", g: 6 },
    ],
  },
  {
    name: "Chocolate protein porridge with walnuts",
    mealType: "breakfast",
    prepMinutes: 8,
    keepsDays: 1,
    method: "1. Cook oats in the milk with the cocoa.\n2. Beat in the whey off the heat.\n3. Scatter walnuts.",
    lines: [
      { n: "Rolled oats", g: 55, scale: [35, 85] },
      { n: "Semi-skimmed milk", g: 200, scale: [130, 300] },
      { n: "Whey protein powder", g: 30, scale: [18, 40] },
      { n: "Cocoa powder", g: 8 },
      { n: "Walnuts", g: 12 },
    ],
  },

  /* ══ LUNCHES (30) ═════════════════════════════════════════════════════════ */
  {
    name: "Chicken and chickpea salad with feta",
    mealType: "lunch",
    prepMinutes: 15,
    batchFriendly: true,
    keepsDays: 2,
    method: "1. Grill and slice the chicken.\n2. Toss chickpeas, cucumber, tomatoes and leaves with oil and lemon.\n3. Crumble feta over.",
    lines: [
      { n: "Chicken breast", g: 170, scale: [120, 240] },
      { n: "Chickpeas", g: 100, scale: [60, 160] },
      { n: "Feta", g: 40 },
      { n: "Cucumber", g: 80 },
      { n: "Cherry tomatoes", g: 100 },
      { n: "Salad leaves", g: 40 },
      { n: "Olive oil", g: 12 },
      { n: "Lemon", g: 10 },
    ],
  },
  {
    name: "Harissa chicken wrap",
    mealType: "lunch",
    prepMinutes: 12,
    keepsDays: 1,
    method: "1. Rub the chicken in harissa, grill and slice.\n2. Spread yoghurt over the wrap.\n3. Fill with chicken, avocado, leaves and onion.",
    lines: [
      { n: "Chicken breast", g: 160, scale: [110, 240] },
      { n: "Tortilla wraps", g: 62 },
      { n: "Avocado", g: 50 },
      { n: "Harissa paste", g: 15 },
      { n: "Greek yoghurt (0% fat)", g: 40 },
      { n: "Salad leaves", g: 30 },
      { n: "Red onion", g: 25 },
      { n: "Cherry tomatoes", g: 60 },
    ],
  },
  {
    name: "Chicken Caesar-style salad",
    mealType: "lunch",
    prepMinutes: 15,
    keepsDays: 1,
    method: "1. Grill the chicken, slice.\n2. Toast torn sourdough in a little oil for croutons.\n3. Whisk yoghurt, mayo and anchovy into a dressing, toss with romaine and parmesan.",
    lines: [
      { n: "Chicken breast", g: 170, scale: [120, 240] },
      { n: "Romaine lettuce", g: 120 },
      { n: "Parmesan", g: 25 },
      { n: "Sourdough bread", g: 40, scale: [20, 80] },
      { n: "Mayonnaise (light)", g: 25 },
      { n: "Greek yoghurt (0% fat)", g: 30 },
      { n: "Anchovies", g: 5 },
    ],
  },
  {
    name: "Turkey, bacon and avocado club",
    mealType: "lunch",
    prepMinutes: 12,
    keepsDays: 1,
    method: "1. Grill the turkey steak and bacon.\n2. Toast the sourdough.\n3. Layer with avocado, tomato, leaves and a little mayo.",
    lines: [
      { n: "Turkey breast steak", g: 120, scale: [80, 180] },
      { n: "Bacon medallions", g: 40, scale: [20, 70] },
      { n: "Sourdough bread", g: 110, scale: [70, 160] },
      { n: "Avocado", g: 50 },
      { n: "Tomatoes", g: 60 },
      { n: "Salad leaves", g: 20 },
      { n: "Mayonnaise (light)", g: 15 },
    ],
  },
  {
    name: "Beef and black bean burrito bowl",
    mealType: "lunch",
    prepMinutes: 20,
    batchFriendly: true,
    leftoversFreeze: true,
    keepsDays: 3,
    method: "1. Brown the mince with cumin.\n2. Warm the beans through.\n3. Build over rice with pepper, sweetcorn and soured cream.",
    lines: [
      { n: "Beef mince (5% fat)", g: 150, scale: [100, 220] },
      { n: "Black beans", g: 100, scale: [60, 150] },
      { n: "Basmati rice", g: 65, scale: [40, 100], note: "dry weight" },
      { n: "Red pepper", g: 60 },
      { n: "Sweetcorn", g: 40 },
      { n: "Soured cream", g: 25 },
      { n: "Cumin", g: 2 },
    ],
  },
  {
    name: "Chicken tikka rice bowl",
    mealType: "lunch",
    prepMinutes: 20,
    batchFriendly: true,
    keepsDays: 2,
    method: "1. Marinate the thigh in yoghurt and garam masala.\n2. Grill hard until charred at the edges.\n3. Serve on rice with cucumber and red onion.",
    lines: [
      { n: "Chicken thigh (boneless)", g: 170, scale: [120, 240] },
      { n: "Basmati rice", g: 65, scale: [40, 100], note: "dry weight" },
      { n: "Greek yoghurt (0% fat)", g: 60 },
      { n: "Cucumber", g: 60 },
      { n: "Red onion", g: 30 },
      { n: "Garam masala", g: 4 },
    ],
  },
  {
    name: "Pork and apple slaw pitta",
    mealType: "lunch",
    prepMinutes: 15,
    keepsDays: 1,
    method: "1. Grill the pork, slice thinly.\n2. Shred cabbage, carrot and apple, dress with mayo.\n3. Stuff the pitta.",
    lines: [
      { n: "Pork loin steak", g: 160, scale: [110, 230] },
      { n: "Pitta bread", g: 60 },
      { n: "Cabbage (white)", g: 80 },
      { n: "Carrots", g: 50 },
      { n: "Apple", g: 60 },
      { n: "Mayonnaise (light)", g: 20 },
    ],
  },
  {
    name: "Lamb kofta pitta with tzatziki",
    mealType: "lunch",
    prepMinutes: 20,
    batchFriendly: true,
    leftoversFreeze: true,
    keepsDays: 2,
    method: "1. Mix lamb with cumin, shape into fingers, grill.\n2. Stir grated cucumber into the yoghurt.\n3. Fill the pitta, crumble feta over.",
    lines: [
      { n: "Lamb mince (10% fat)", g: 140, scale: [100, 200] },
      { n: "Pitta bread", g: 60 },
      { n: "Feta", g: 25 },
      { n: "Greek yoghurt (0% fat)", g: 60 },
      { n: "Cucumber", g: 50 },
      { n: "Salad leaves", g: 25 },
      { n: "Cumin", g: 2 },
    ],
  },
  {
    name: "Chicken pesto pasta salad",
    mealType: "lunch",
    prepMinutes: 18,
    batchFriendly: true,
    keepsDays: 2,
    method: "1. Cook and cool the pasta.\n2. Toss with pesto, chicken and tomatoes.\n3. Fold rocket through, shave parmesan over.",
    lines: [
      { n: "Chicken breast", g: 160, scale: [110, 240] },
      { n: "Pasta (penne)", g: 75, scale: [50, 110], note: "dry weight" },
      { n: "Pesto", g: 20 },
      { n: "Cherry tomatoes", g: 80 },
      { n: "Rocket", g: 25 },
      { n: "Parmesan", g: 15 },
    ],
  },
  {
    name: "Gammon, egg and new potatoes",
    mealType: "lunch",
    prepMinutes: 20,
    keepsDays: 2,
    method: "1. Boil the potatoes.\n2. Griddle the gammon.\n3. Fry the eggs, serve with peas.",
    lines: [
      { n: "Gammon steak", g: 150, scale: [100, 220] },
      { n: "Eggs", g: 116, scale: [58, 174] },
      { n: "New potatoes", g: 200, scale: [130, 300] },
      { n: "Frozen peas", g: 80 },
      { n: "Olive oil", g: 8 },
    ],
  },
  {
    name: "Turkey chilli jacket potato",
    mealType: "lunch",
    prepMinutes: 25,
    batchFriendly: true,
    leftoversFreeze: true,
    keepsDays: 3,
    method: "1. Bake the potato until the skin crisps.\n2. Brown turkey with cumin, add beans and tomatoes, simmer 15 min.\n3. Split the potato, pile on, top with cheddar.",
    lines: [
      { n: "Turkey mince (5% fat)", g: 140, scale: [90, 200] },
      { n: "Potatoes", g: 280, scale: [180, 400] },
      { n: "Kidney beans", g: 80, scale: [50, 130] },
      { n: "Chopped tomatoes", g: 100 },
      { n: "Cheddar", g: 25 },
      { n: "Cumin", g: 2 },
    ],
  },
  {
    name: "Chicken noodle salad with peanut dressing",
    mealType: "lunch",
    prepMinutes: 18,
    keepsDays: 2,
    method: "1. Soak the noodles, refresh cold.\n2. Whisk peanut butter, soy and lime into a dressing.\n3. Toss with chicken, carrot and beansprouts.",
    lines: [
      { n: "Chicken breast", g: 160, scale: [110, 240] },
      { n: "Rice noodles", g: 70, scale: [45, 110], note: "dry weight" },
      { n: "Peanut butter", g: 20 },
      { n: "Carrots", g: 60 },
      { n: "Beansprouts", g: 60 },
      { n: "Soy sauce", g: 10 },
      { n: "Lime", g: 10 },
    ],
  },
  {
    name: "Roast beef and rocket sandwich",
    mealType: "lunch",
    prepMinutes: 12,
    keepsDays: 1,
    method: "1. Sear the steak rare, rest, slice thinly.\n2. Spread mustard on the sourdough.\n3. Pile on beef, rocket and tomato.",
    lines: [
      { n: "Beef rump steak", g: 150, scale: [100, 220] },
      { n: "Sourdough bread", g: 110, scale: [70, 160] },
      { n: "Rocket", g: 25 },
      { n: "Tomatoes", g: 60 },
      { n: "Wholegrain mustard", g: 10 },
    ],
  },
  {
    name: "Chicken shawarma bowl with tahini",
    mealType: "lunch",
    prepMinutes: 22,
    batchFriendly: true,
    keepsDays: 2,
    method: "1. Toss the thigh in ras el hanout, roast 20 min.\n2. Soak the bulgur.\n3. Loosen tahini with water and lemon, spoon over.",
    lines: [
      { n: "Chicken thigh (boneless)", g: 170, scale: [120, 240] },
      { n: "Bulgur wheat", g: 60, scale: [40, 95], note: "dry weight" },
      { n: "Tahini", g: 15 },
      { n: "Cucumber", g: 60 },
      { n: "Tomatoes", g: 60 },
      { n: "Red onion", g: 30 },
      { n: "Ras el hanout", g: 3 },
    ],
  },
  {
    name: "Chorizo, chicken and butter bean soup",
    mealType: "lunch",
    prepMinutes: 30,
    batchFriendly: true,
    leftoversFreeze: true,
    keepsDays: 4,
    method: "1. Render the chorizo, soften the onion in its oil.\n2. Add chicken, tomatoes, beans and stock, simmer 20 min.\n3. Wilt the kale through at the end.",
    lines: [
      { n: "Chicken breast", g: 100, scale: [70, 150] },
      { n: "Chorizo", g: 60, scale: [40, 90] },
      { n: "Butter beans", g: 150, scale: [100, 220] },
      { n: "Chopped tomatoes", g: 150 },
      { n: "Kale", g: 60 },
      { n: "Onion", g: 50 },
      { n: "Stock cubes", g: 8 },
    ],
  },
  {
    name: "Chicken, bacon and avocado salad",
    mealType: "lunch",
    prepMinutes: 18,
    keepsDays: 1,
    method: "1. Grill chicken and bacon.\n2. Boil and halve the new potatoes.\n3. Toss everything with leaves, oil and balsamic.",
    lines: [
      { n: "Chicken breast", g: 160, scale: [110, 240] },
      { n: "Bacon medallions", g: 40, scale: [20, 70] },
      { n: "New potatoes", g: 120, scale: [70, 200] },
      { n: "Avocado", g: 60 },
      { n: "Salad leaves", g: 50 },
      { n: "Cherry tomatoes", g: 80 },
      { n: "Olive oil", g: 10 },
      { n: "Balsamic vinegar", g: 10 },
    ],
  },
  {
    name: "Turkey meatball sub",
    mealType: "lunch",
    prepMinutes: 25,
    batchFriendly: true,
    leftoversFreeze: true,
    keepsDays: 3,
    method: "1. Roll the turkey with oregano into balls, brown.\n2. Simmer in passata 15 min.\n3. Load into split sourdough, melt mozzarella over.",
    lines: [
      { n: "Turkey mince (5% fat)", g: 150, scale: [100, 220] },
      { n: "Sourdough bread", g: 100, scale: [60, 150] },
      { n: "Passata", g: 100 },
      { n: "Mozzarella", g: 40 },
      { n: "Dried oregano", g: 1 },
    ],
  },
  {
    name: "Chicken and sweetcorn rice bowl",
    mealType: "lunch",
    prepMinutes: 18,
    batchFriendly: true,
    keepsDays: 2,
    method: "1. Cook the rice.\n2. Fry the chicken in sesame oil until golden.\n3. Fold in sweetcorn, spring onion and soy.",
    lines: [
      { n: "Chicken breast", g: 170, scale: [120, 240] },
      { n: "Basmati rice", g: 70, scale: [45, 105], note: "dry weight" },
      { n: "Sweetcorn", g: 80 },
      { n: "Spring onion", g: 20 },
      { n: "Soy sauce", g: 10 },
      { n: "Sesame oil", g: 5 },
    ],
  },
  {
    name: "Pork banh mi wrap",
    mealType: "lunch",
    prepMinutes: 18,
    keepsDays: 1,
    method: "1. Grill the tenderloin, slice thin.\n2. Pickle carrot and cucumber in a little vinegar.\n3. Fill the wrap, add coriander, peanuts and sriracha.",
    lines: [
      { n: "Pork tenderloin", g: 160, scale: [110, 230] },
      { n: "Tortilla wraps", g: 62 },
      { n: "Peanuts", g: 15 },
      { n: "Carrots", g: 60 },
      { n: "Cucumber", g: 50 },
      { n: "Fresh coriander", g: 5 },
      { n: "Sriracha", g: 10 },
      { n: "Mayonnaise (light)", g: 15 },
    ],
  },
  {
    name: "Chicken satay skewers with rice",
    mealType: "lunch",
    prepMinutes: 22,
    batchFriendly: true,
    keepsDays: 2,
    method: "1. Skewer and grill the chicken.\n2. Warm peanut butter with coconut milk and soy into a sauce.\n3. Serve over rice with sugar snaps.",
    lines: [
      { n: "Chicken breast", g: 170, scale: [120, 240] },
      { n: "Basmati rice", g: 65, scale: [40, 100], note: "dry weight" },
      { n: "Peanut butter", g: 22 },
      { n: "Coconut milk", g: 30 },
      { n: "Sugar snap peas", g: 60 },
      { n: "Soy sauce", g: 8 },
    ],
  },
  {
    name: "Gammon and pea soup with sourdough",
    mealType: "lunch",
    prepMinutes: 30,
    batchFriendly: true,
    leftoversFreeze: true,
    keepsDays: 4,
    method: "1. Simmer gammon, potato and onion in stock 20 min.\n2. Add peas, cook 5 min, blend half.\n3. Shred the gammon back in, serve with sourdough.",
    lines: [
      { n: "Gammon steak", g: 130, scale: [90, 190] },
      { n: "Frozen peas", g: 150, scale: [100, 220] },
      { n: "Potatoes", g: 120 },
      { n: "Sourdough bread", g: 60, scale: [30, 100] },
      { n: "Onion", g: 50 },
      { n: "Stock cubes", g: 8 },
      { n: "Fresh parsley", g: 5 },
    ],
  },
  {
    name: "Chicken sausage, bean and spinach stew",
    mealType: "lunch",
    prepMinutes: 25,
    batchFriendly: true,
    leftoversFreeze: true,
    keepsDays: 3,
    method: "1. Brown the sausages, slice.\n2. Soften onion, add tomatoes and beans, simmer 15 min.\n3. Wilt spinach through, mop up with sourdough.",
    lines: [
      { n: "Chicken sausages", g: 150, scale: [100, 220] },
      { n: "Cannellini beans", g: 150, scale: [100, 220] },
      { n: "Chopped tomatoes", g: 150 },
      { n: "Sourdough bread", g: 40, scale: [0, 90] },
      { n: "Spinach", g: 60 },
      { n: "Onion", g: 50 },
      { n: "Olive oil", g: 8 },
    ],
  },
  {
    name: "Tuna niçoise salad",
    mealType: "lunch",
    prepMinutes: 20,
    keepsDays: 1,
    method: "1. Boil potatoes and beans, cool.\n2. Soft-boil the eggs.\n3. Toss everything with olives, tomatoes and oil.",
    lines: [
      { n: "Tinned tuna", g: 120, scale: [80, 170] },
      { n: "Eggs", g: 116, scale: [58, 174] },
      { n: "New potatoes", g: 150, scale: [90, 240] },
      { n: "Green beans", g: 80 },
      { n: "Black olives", g: 25 },
      { n: "Cherry tomatoes", g: 80 },
      { n: "Olive oil", g: 12 },
    ],
  },
  {
    name: "Smoked mackerel and beetroot salad",
    mealType: "lunch",
    prepMinutes: 15,
    keepsDays: 1,
    method: "1. Boil and halve the potatoes.\n2. Soft-boil the eggs.\n3. Flake mackerel over beetroot and rocket, dress with yoghurt and mustard.",
    lines: [
      { n: "Smoked mackerel", g: 90, scale: [60, 130] },
      { n: "Eggs", g: 116, scale: [58, 174] },
      { n: "Cooked beetroot", g: 120 },
      { n: "New potatoes", g: 150, scale: [90, 240] },
      { n: "Rocket", g: 30 },
      { n: "Greek yoghurt (0% fat)", g: 50 },
      { n: "Wholegrain mustard", g: 8 },
    ],
  },
  {
    name: "Prawn and avocado open sandwich",
    mealType: "lunch",
    prepMinutes: 10,
    keepsDays: 1,
    method: "1. Toast the sourdough.\n2. Mash the avocado over it with lemon.\n3. Pile on prawns bound in a little mayo, top with rocket.",
    lines: [
      { n: "King prawns", g: 200, scale: [140, 280] },
      { n: "Sourdough bread", g: 90, scale: [55, 140] },
      { n: "Avocado", g: 60 },
      { n: "Mayonnaise (light)", g: 20 },
      { n: "Rocket", g: 20 },
      { n: "Lemon", g: 10 },
    ],
  },
  {
    name: "Salmon and quinoa salad",
    mealType: "lunch",
    prepMinutes: 22,
    keepsDays: 2,
    method: "1. Roast the salmon 14 min.\n2. Cook the quinoa, cool.\n3. Toss with edamame, cucumber, tomatoes and lemon; flake salmon over.",
    lines: [
      { n: "Salmon fillet", g: 140, scale: [100, 190] },
      { n: "Quinoa", g: 60, scale: [40, 95], note: "dry weight" },
      { n: "Edamame beans", g: 60 },
      { n: "Cucumber", g: 60 },
      { n: "Cherry tomatoes", g: 60 },
      { n: "Spinach", g: 40 },
      { n: "Lemon", g: 10 },
    ],
  },
  {
    name: "Halloumi, lentil and roasted pepper salad",
    mealType: "lunch",
    prepMinutes: 20,
    keepsDays: 2,
    method: "1. Roast the pepper.\n2. Cook the lentils.\n3. Fry halloumi 2 min a side, toss everything with oil and balsamic.",
    lines: [
      { n: "Halloumi", g: 100, scale: [70, 140] },
      { n: "Puy lentils", g: 45, scale: [30, 75], note: "dry weight" },
      { n: "Edamame beans", g: 50 },
      { n: "Red pepper", g: 80 },
      { n: "Rocket", g: 30 },
      { n: "Olive oil", g: 5 },
      { n: "Balsamic vinegar", g: 10 },
    ],
  },
  {
    name: "Egg, cottage cheese and avocado salad",
    mealType: "lunch",
    prepMinutes: 12,
    keepsDays: 1,
    method: "1. Hard-boil and quarter the eggs.\n2. Spoon cottage cheese over the leaves.\n3. Add avocado and tomatoes, serve with oatcakes.",
    lines: [
      { n: "Eggs", g: 174, scale: [116, 232] },
      { n: "Cottage cheese", g: 150, scale: [100, 220] },
      { n: "Oatcakes", g: 33, scale: [11, 55] },
      { n: "Avocado", g: 50 },
      { n: "Salad leaves", g: 40 },
      { n: "Cherry tomatoes", g: 80 },
    ],
  },
  {
    name: "Salmon fishcakes with salad",
    mealType: "lunch",
    prepMinutes: 25,
    batchFriendly: true,
    leftoversFreeze: true,
    keepsDays: 3,
    method: "1. Boil and mash the potato, cool.\n2. Mix with salmon and egg, shape, coat in panko.\n3. Fry until golden, serve with leaves.",
    lines: [
      { n: "Tinned salmon", g: 140, scale: [100, 190] },
      { n: "Potatoes", g: 180, scale: [120, 260] },
      { n: "Eggs", g: 58 },
      { n: "Panko breadcrumbs", g: 25 },
      { n: "Salad leaves", g: 40 },
      { n: "Olive oil", g: 8 },
    ],
  },
  {
    name: "Tofu, edamame and quinoa bowl",
    mealType: "lunch",
    prepMinutes: 20,
    batchFriendly: true,
    keepsDays: 2,
    method: "1. Press and cube the tofu, fry hard in sesame oil.\n2. Cook the quinoa.\n3. Toss with edamame, pepper, soy and spring onion.",
    lines: [
      { n: "Tofu (firm)", g: 200, scale: [140, 280] },
      { n: "Quinoa", g: 55, scale: [35, 90], note: "dry weight" },
      { n: "Edamame beans", g: 80 },
      { n: "Red pepper", g: 60 },
      { n: "Spring onion", g: 20 },
      { n: "Soy sauce", g: 10 },
      { n: "Sesame oil", g: 6 },
    ],
  },

  /* ══ DINNERS (50) — every one contains meat ═══════════════════════════════ */
  {
    name: "Harissa chicken thighs with bulgur and feta",
    mealType: "dinner",
    prepMinutes: 35,
    batchFriendly: true,
    keepsDays: 3,
    method: "1. Toss thighs in harissa, roast 25 min at 200C.\n2. Roast courgette alongside.\n3. Soak the bulgur, crumble feta over the lot.",
    lines: [
      { n: "Chicken thigh (boneless)", g: 190, scale: [130, 260] },
      { n: "Bulgur wheat", g: 55, scale: [35, 90], note: "dry weight" },
      { n: "Feta", g: 35 },
      { n: "Courgette", g: 100 },
      { n: "Harissa paste", g: 20 },
      { n: "Olive oil", g: 8 },
    ],
  },
  {
    name: "Lemon and thyme chicken with new potatoes",
    mealType: "dinner",
    prepMinutes: 35,
    keepsDays: 3,
    method: "1. Roast potatoes and carrots in oil 30 min at 200C.\n2. Add chicken with lemon and thyme for the last 18 min.\n3. Steam the tenderstem.",
    lines: [
      { n: "Chicken breast", g: 200, scale: [140, 280] },
      { n: "New potatoes", g: 250, scale: [160, 380] },
      { n: "Tenderstem broccoli", g: 100 },
      { n: "Carrots", g: 80 },
      { n: "Olive oil", g: 12 },
      { n: "Lemon", g: 20 },
      { n: "Dried thyme", g: 2 },
    ],
  },
  {
    name: "Chicken katsu with rice",
    mealType: "dinner",
    prepMinutes: 35,
    keepsDays: 2,
    method: "1. Flatten and crumb the chicken in panko, bake 20 min.\n2. Soften carrot and onion, add curry powder and coconut milk, simmer and blend.\n3. Slice over rice, sauce poured on.",
    lines: [
      { n: "Chicken breast", g: 180, scale: [110, 250] },
      { n: "Panko breadcrumbs", g: 30, scale: [18, 40] },
      { n: "Basmati rice", g: 55, scale: [35, 90], note: "dry weight" },
      { n: "Coconut milk", g: 40 },
      { n: "Carrots", g: 60 },
      { n: "Curry powder", g: 6 },
      { n: "Olive oil", g: 6 },
    ],
  },
  {
    name: "Thai red curry chicken",
    mealType: "dinner",
    prepMinutes: 30,
    batchFriendly: true,
    leftoversFreeze: true,
    keepsDays: 3,
    method: "1. Fry the paste 1 min.\n2. Add chicken, brown, then coconut milk and fish sauce, simmer 15 min.\n3. Add pepper and sugar snaps for the last 4 min. Serve on rice.",
    lines: [
      { n: "Chicken thigh (boneless)", g: 180, scale: [130, 250] },
      { n: "Coconut milk", g: 70 },
      { n: "Basmati rice", g: 60, scale: [40, 95], note: "dry weight" },
      { n: "Thai red curry paste", g: 25 },
      { n: "Sugar snap peas", g: 70 },
      { n: "Red pepper", g: 60 },
      { n: "Fish sauce", g: 8 },
    ],
  },
  {
    name: "Chicken fajitas",
    mealType: "dinner",
    prepMinutes: 25,
    keepsDays: 2,
    method: "1. Fry strips of chicken hard with paprika.\n2. Add pepper and onion, keep the heat high.\n3. Warm the wraps, serve with soured cream.",
    lines: [
      { n: "Chicken breast", g: 190, scale: [130, 270] },
      { n: "Tortilla wraps", g: 124, scale: [62, 186] },
      { n: "Red pepper", g: 80 },
      { n: "Onion", g: 60 },
      { n: "Soured cream", g: 25 },
      { n: "Smoked paprika", g: 3 },
    ],
  },
  {
    name: "Chicken and chorizo paella",
    mealType: "dinner",
    prepMinutes: 40,
    batchFriendly: true,
    keepsDays: 3,
    method: "1. Render the chorizo, brown the chicken in its oil.\n2. Soften onion and pepper, stir in paprika and rice.\n3. Add stock, simmer 18 min undisturbed, peas in at the end.",
    lines: [
      { n: "Chicken thigh (boneless)", g: 150, scale: [100, 220] },
      { n: "Chorizo", g: 40, scale: [25, 65] },
      { n: "Basmati rice", g: 55, scale: [35, 90], note: "dry weight" },
      { n: "Red pepper", g: 60 },
      { n: "Frozen peas", g: 60 },
      { n: "Onion", g: 50 },
      { n: "Stock cubes", g: 6 },
      { n: "Smoked paprika", g: 3 },
    ],
  },
  {
    name: "Butter chicken with rice",
    mealType: "dinner",
    prepMinutes: 35,
    batchFriendly: true,
    leftoversFreeze: true,
    keepsDays: 3,
    method: "1. Brown the chicken in butter, set aside.\n2. Soften onion, add garam masala and tomatoes, simmer 15 min.\n3. Stir in creme fraiche, return chicken. Serve on rice.",
    lines: [
      { n: "Chicken breast", g: 190, scale: [130, 270] },
      { n: "Basmati rice", g: 65, scale: [40, 100], note: "dry weight" },
      { n: "Chopped tomatoes", g: 150 },
      { n: "Creme fraiche (half fat)", g: 50 },
      { n: "Onion", g: 50 },
      { n: "Butter", g: 8 },
      { n: "Garam masala", g: 5 },
    ],
  },
  {
    name: "Chicken, leek and mushroom gnocchi bake",
    mealType: "dinner",
    prepMinutes: 35,
    batchFriendly: true,
    keepsDays: 3,
    method: "1. Fry mushrooms and leek hard.\n2. Add chicken, then creme fraiche, loosen with a splash of water.\n3. Fold in boiled gnocchi, top with parmesan, grill until blistered.",
    lines: [
      { n: "Chicken breast", g: 190, scale: [130, 270] },
      { n: "Gnocchi", g: 150, scale: [100, 230] },
      { n: "Mushrooms", g: 100 },
      { n: "Leek", g: 80 },
      { n: "Creme fraiche (half fat)", g: 40 },
      { n: "Parmesan", g: 20 },
    ],
  },
  {
    name: "Grilled chicken with sweet potato mash",
    mealType: "dinner",
    prepMinutes: 30,
    keepsDays: 3,
    method: "1. Boil and mash the sweet potato with butter.\n2. Griddle the chicken.\n3. Wilt the kale in oil and garlic.",
    lines: [
      { n: "Chicken breast", g: 200, scale: [140, 280] },
      { n: "Sweet potato", g: 250, scale: [160, 380] },
      { n: "Kale", g: 80 },
      { n: "Olive oil", g: 10 },
      { n: "Butter", g: 8 },
    ],
  },
  {
    name: "Chicken shawarma with flatbread",
    mealType: "dinner",
    prepMinutes: 30,
    batchFriendly: true,
    keepsDays: 3,
    method: "1. Toss thighs in ras el hanout, roast 25 min.\n2. Loosen the tahini with lemon and water.\n3. Pile onto warm flatbread with yoghurt, tomato and onion.",
    lines: [
      { n: "Chicken thigh (boneless)", g: 180, scale: [130, 250] },
      { n: "Flatbread", g: 80, scale: [40, 120] },
      { n: "Greek yoghurt (0% fat)", g: 60 },
      { n: "Tahini", g: 12 },
      { n: "Tomatoes", g: 60 },
      { n: "Red onion", g: 30 },
      { n: "Ras el hanout", g: 3 },
    ],
  },
  {
    name: "Sticky hoisin chicken with noodles",
    mealType: "dinner",
    prepMinutes: 25,
    keepsDays: 2,
    method: "1. Fry the chicken hard, glaze with hoisin at the end.\n2. Stir-fry pak choi and beansprouts in sesame oil.\n3. Toss through cooked noodles, scatter spring onion.",
    lines: [
      { n: "Chicken breast", g: 190, scale: [130, 270] },
      { n: "Egg noodles", g: 70, scale: [45, 110], note: "dry weight" },
      { n: "Hoisin sauce", g: 30 },
      { n: "Pak choi", g: 100 },
      { n: "Beansprouts", g: 60 },
      { n: "Spring onion", g: 20 },
      { n: "Sesame oil", g: 8 },
    ],
  },
  {
    name: "Chicken, bacon and spinach pasta",
    mealType: "dinner",
    prepMinutes: 25,
    batchFriendly: true,
    keepsDays: 2,
    method: "1. Crisp the bacon, brown the chicken in the fat.\n2. Stir in cream cheese with a ladle of pasta water.\n3. Fold through pasta and spinach, parmesan over.",
    lines: [
      { n: "Chicken breast", g: 170, scale: [120, 240] },
      { n: "Bacon medallions", g: 50, scale: [30, 80] },
      { n: "Wholewheat pasta", g: 75, scale: [50, 110], note: "dry weight" },
      { n: "Light cream cheese", g: 40 },
      { n: "Spinach", g: 60 },
      { n: "Parmesan", g: 15 },
    ],
  },
  {
    name: "Turkey and black bean chilli",
    mealType: "dinner",
    prepMinutes: 35,
    batchFriendly: true,
    leftoversFreeze: true,
    keepsDays: 4,
    method: "1. Brown the turkey hard.\n2. Soften onion, add cumin and chilli, then tomatoes and beans.\n3. Simmer 25 min. Serve on rice.",
    lines: [
      { n: "Turkey mince (5% fat)", g: 170, scale: [120, 240] },
      { n: "Black beans", g: 120, scale: [80, 180] },
      { n: "Basmati rice", g: 60, scale: [40, 95], note: "dry weight" },
      { n: "Chopped tomatoes", g: 150 },
      { n: "Onion", g: 50 },
      { n: "Olive oil", g: 8 },
      { n: "Cumin", g: 3 },
      { n: "Chilli flakes", g: 1 },
    ],
  },
  {
    name: "Turkey burgers with sweet potato wedges",
    mealType: "dinner",
    prepMinutes: 35,
    batchFriendly: true,
    leftoversFreeze: true,
    keepsDays: 3,
    method: "1. Roast sweet potato wedges 30 min at 200C.\n2. Shape and griddle the turkey patties.\n3. Build in a toasted muffin with tomato and leaves.",
    lines: [
      { n: "Turkey mince (5% fat)", g: 180, scale: [120, 250] },
      { n: "Sweet potato", g: 250, scale: [160, 380] },
      { n: "English muffins", g: 67 },
      { n: "Tomatoes", g: 40 },
      { n: "Salad leaves", g: 20 },
      { n: "Olive oil", g: 10 },
    ],
  },
  {
    name: "Turkey stir-fry with pak choi and noodles",
    mealType: "dinner",
    prepMinutes: 20,
    keepsDays: 2,
    method: "1. Sear strips of turkey in sesame oil.\n2. Add ginger, baby corn and pak choi, keep it moving.\n3. Toss through noodles with soy.",
    lines: [
      { n: "Turkey breast steak", g: 190, scale: [130, 270] },
      { n: "Egg noodles", g: 70, scale: [45, 110], note: "dry weight" },
      { n: "Pak choi", g: 100 },
      { n: "Baby corn", g: 70 },
      { n: "Soy sauce", g: 12 },
      { n: "Sesame oil", g: 8 },
      { n: "Ginger", g: 5 },
    ],
  },
  {
    name: "Turkey bolognese with spaghetti",
    mealType: "dinner",
    prepMinutes: 35,
    batchFriendly: true,
    leftoversFreeze: true,
    keepsDays: 4,
    method: "1. Brown the turkey.\n2. Soften onion and carrot, add passata, simmer 25 min.\n3. Toss with spaghetti, parmesan over.",
    lines: [
      { n: "Turkey mince (5% fat)", g: 170, scale: [120, 240] },
      { n: "Spaghetti", g: 70, scale: [45, 110], note: "dry weight" },
      { n: "Passata", g: 150 },
      { n: "Onion", g: 50 },
      { n: "Carrots", g: 50 },
      { n: "Parmesan", g: 15 },
      { n: "Olive oil", g: 8 },
    ],
  },
  {
    name: "Turkey and vegetable traybake with couscous",
    mealType: "dinner",
    prepMinutes: 35,
    batchFriendly: true,
    keepsDays: 3,
    method: "1. Toss vegetables in oil and ras el hanout, roast 25 min.\n2. Add turkey steaks for the last 15 min.\n3. Soak the couscous in stock, fork through.",
    lines: [
      { n: "Turkey breast steak", g: 190, scale: [130, 270] },
      { n: "Couscous", g: 65, scale: [40, 100], note: "dry weight" },
      { n: "Courgette", g: 100 },
      { n: "Red pepper", g: 80 },
      { n: "Red onion", g: 60 },
      { n: "Olive oil", g: 12 },
      { n: "Ras el hanout", g: 3 },
    ],
  },
  {
    name: "Beef ragu with red lentils",
    mealType: "dinner",
    prepMinutes: 45,
    batchFriendly: true,
    leftoversFreeze: true,
    keepsDays: 4,
    method: "1. Brown the mince hard, set aside.\n2. Soften onion and carrot, add lentils, passata and a splash of water.\n3. Return the beef, simmer 30 min. Serve with pasta and parmesan.",
    lines: [
      { n: "Beef mince (5% fat)", g: 150, scale: [100, 220] },
      { n: "Red lentils", g: 30, scale: [20, 50], note: "dry weight" },
      { n: "Wholewheat pasta", g: 65, scale: [40, 100], note: "dry weight" },
      { n: "Passata", g: 150 },
      { n: "Onion", g: 50 },
      { n: "Carrots", g: 50 },
      { n: "Parmesan", g: 15 },
    ],
  },
  {
    name: "Beef stir-fry with broccoli and rice",
    mealType: "dinner",
    prepMinutes: 22,
    keepsDays: 2,
    method: "1. Sear thin strips of steak in a very hot pan, remove.\n2. Fry garlic, ginger and broccoli.\n3. Return the beef with soy, serve on rice.",
    lines: [
      { n: "Beef rump steak", g: 180, scale: [120, 250] },
      { n: "Basmati rice", g: 65, scale: [40, 100], note: "dry weight" },
      { n: "Broccoli", g: 120 },
      { n: "Soy sauce", g: 12 },
      { n: "Sesame oil", g: 8 },
      { n: "Ginger", g: 5 },
      { n: "Garlic", g: 6 },
    ],
  },
  {
    name: "Steak with new potatoes and asparagus",
    mealType: "dinner",
    prepMinutes: 30,
    keepsDays: 2,
    method: "1. Boil the potatoes, crush lightly with butter.\n2. Sear the steak 3 min a side, rest 5.\n3. Griddle the asparagus in oil.",
    lines: [
      { n: "Beef rump steak", g: 200, scale: [140, 280] },
      { n: "New potatoes", g: 250, scale: [160, 380] },
      { n: "Asparagus", g: 100 },
      { n: "Butter", g: 10 },
      { n: "Olive oil", g: 8 },
    ],
  },
  {
    name: "Beef stew with root vegetables",
    mealType: "dinner",
    prepMinutes: 50,
    batchFriendly: true,
    leftoversFreeze: true,
    keepsDays: 4,
    method: "1. Brown the beef in batches.\n2. Add onion, carrot, parsnip, puree and stock.\n3. Cover and simmer 90 min, potatoes in for the last 30.",
    lines: [
      { n: "Stewing beef", g: 190, scale: [130, 260] },
      { n: "Potatoes", g: 200, scale: [130, 300] },
      { n: "Carrots", g: 100 },
      { n: "Parsnip", g: 80 },
      { n: "Onion", g: 60 },
      { n: "Stock cubes", g: 8 },
      { n: "Tomato puree", g: 15 },
    ],
  },
  {
    name: "Beef koftas with couscous and tzatziki",
    mealType: "dinner",
    prepMinutes: 30,
    batchFriendly: true,
    leftoversFreeze: true,
    keepsDays: 3,
    method: "1. Mix mince with cumin and parsley, shape onto skewers, grill.\n2. Soak the couscous.\n3. Grate cucumber into the yoghurt, season.",
    lines: [
      { n: "Beef mince (5% fat)", g: 170, scale: [120, 240] },
      { n: "Couscous", g: 60, scale: [40, 95], note: "dry weight" },
      { n: "Greek yoghurt (0% fat)", g: 60 },
      { n: "Cucumber", g: 50 },
      { n: "Olive oil", g: 8 },
      { n: "Cumin", g: 3 },
      { n: "Fresh parsley", g: 5 },
    ],
  },
  {
    name: "Beef burrito bowl",
    mealType: "dinner",
    prepMinutes: 25,
    batchFriendly: true,
    keepsDays: 3,
    method: "1. Brown the mince with paprika.\n2. Warm the beans and sweetcorn through.\n3. Build over rice with soured cream and cheddar.",
    lines: [
      { n: "Beef mince (5% fat)", g: 160, scale: [110, 230] },
      { n: "Basmati rice", g: 55, scale: [35, 90], note: "dry weight" },
      { n: "Black beans", g: 80, scale: [50, 130] },
      { n: "Sweetcorn", g: 60 },
      { n: "Soured cream", g: 25 },
      { n: "Cheddar", g: 15 },
      { n: "Smoked paprika", g: 3 },
    ],
  },
  {
    name: "Cottage pie with sweet potato mash",
    mealType: "dinner",
    prepMinutes: 45,
    batchFriendly: true,
    leftoversFreeze: true,
    keepsDays: 4,
    method: "1. Brown the mince with onion and carrot.\n2. Add passata, Worcestershire and peas, simmer 20 min.\n3. Top with buttery sweet potato mash, bake 25 min.",
    lines: [
      { n: "Beef mince (5% fat)", g: 170, scale: [120, 240] },
      { n: "Sweet potato", g: 250, scale: [160, 380] },
      { n: "Carrots", g: 70 },
      { n: "Onion", g: 50 },
      { n: "Passata", g: 100 },
      { n: "Frozen peas", g: 60 },
      { n: "Butter", g: 8 },
      { n: "Worcestershire sauce", g: 8 },
    ],
  },
  {
    name: "Beef and mushroom stroganoff",
    mealType: "dinner",
    prepMinutes: 30,
    keepsDays: 2,
    method: "1. Sear strips of steak, remove.\n2. Brown the mushrooms hard, soften the onion, add paprika.\n3. Stir in soured cream, return the beef. Serve on rice.",
    lines: [
      { n: "Beef rump steak", g: 175, scale: [120, 250] },
      { n: "Basmati rice", g: 60, scale: [40, 95], note: "dry weight" },
      { n: "Mushrooms", g: 120 },
      { n: "Soured cream", g: 50 },
      { n: "Onion", g: 50 },
      { n: "Smoked paprika", g: 3 },
    ],
  },
  {
    name: "Korean beef bowl with gochujang",
    mealType: "dinner",
    prepMinutes: 25,
    batchFriendly: true,
    keepsDays: 3,
    method: "1. Brown the mince, stir in gochujang.\n2. Quick-fry carrot and beansprouts in sesame oil.\n3. Serve on rice with a fried egg and spring onion.",
    lines: [
      { n: "Beef mince (5% fat)", g: 170, scale: [100, 240] },
      { n: "Basmati rice", g: 55, scale: [35, 90], note: "dry weight" },
      { n: "Eggs", g: 58 },
      { n: "Gochujang", g: 25 },
      { n: "Beansprouts", g: 60 },
      { n: "Carrots", g: 60 },
      { n: "Sesame oil", g: 8 },
      { n: "Spring onion", g: 20 },
    ],
  },
  {
    name: "Beef and butter bean casserole",
    mealType: "dinner",
    prepMinutes: 50,
    batchFriendly: true,
    leftoversFreeze: true,
    keepsDays: 4,
    method: "1. Brown the beef.\n2. Add onion, carrot, tomatoes and stock, simmer 90 min.\n3. Stir the butter beans in for the last 15 min.",
    lines: [
      { n: "Stewing beef", g: 180, scale: [120, 250] },
      { n: "Butter beans", g: 150, scale: [100, 220] },
      { n: "Chopped tomatoes", g: 150 },
      { n: "Carrots", g: 80 },
      { n: "Onion", g: 50 },
      { n: "Olive oil", g: 10 },
      { n: "Stock cubes", g: 8 },
    ],
  },
  {
    name: "Pork loin with apple slaw",
    mealType: "dinner",
    prepMinutes: 30,
    keepsDays: 2,
    method: "1. Boil the new potatoes.\n2. Griddle the pork, rest.\n3. Shred cabbage, carrot and apple, dress with mayo and mustard.",
    lines: [
      { n: "Pork loin steak", g: 180, scale: [120, 250] },
      { n: "New potatoes", g: 220, scale: [140, 330] },
      { n: "Cabbage (white)", g: 80 },
      { n: "Carrots", g: 50 },
      { n: "Apple", g: 60 },
      { n: "Mayonnaise (light)", g: 20 },
      { n: "Wholegrain mustard", g: 8 },
    ],
  },
  {
    name: "Pork meatballs with orzo",
    mealType: "dinner",
    prepMinutes: 30,
    batchFriendly: true,
    leftoversFreeze: true,
    keepsDays: 3,
    method: "1. Roll pork with oregano into balls, brown.\n2. Add passata and onion, simmer 20 min.\n3. Stir cooked orzo through, parmesan over.",
    lines: [
      { n: "Pork mince (10% fat)", g: 160, scale: [110, 230] },
      { n: "Orzo", g: 70, scale: [45, 110], note: "dry weight" },
      { n: "Passata", g: 150 },
      { n: "Onion", g: 40 },
      { n: "Parmesan", g: 15 },
      { n: "Dried oregano", g: 2 },
    ],
  },
  {
    name: "Sticky pork stir-fry",
    mealType: "dinner",
    prepMinutes: 22,
    keepsDays: 2,
    method: "1. Sear sliced tenderloin in sesame oil.\n2. Add broccoli, then sweet chilli and soy.\n3. Reduce until glossy, serve on rice.",
    lines: [
      { n: "Pork tenderloin", g: 190, scale: [130, 260] },
      { n: "Basmati rice", g: 65, scale: [40, 100], note: "dry weight" },
      { n: "Broccoli", g: 100 },
      { n: "Sweet chilli sauce", g: 25 },
      { n: "Soy sauce", g: 10 },
      { n: "Sesame oil", g: 8 },
    ],
  },
  {
    name: "Pork tenderloin with mustard sauce and mash",
    mealType: "dinner",
    prepMinutes: 30,
    keepsDays: 2,
    method: "1. Boil and mash the potatoes with butter.\n2. Sear the tenderloin, rest.\n3. Deglaze with creme fraiche and mustard, pour over. Steam the beans.",
    lines: [
      { n: "Pork tenderloin", g: 190, scale: [130, 260] },
      { n: "Potatoes", g: 250, scale: [160, 370] },
      { n: "Green beans", g: 100 },
      { n: "Creme fraiche (half fat)", g: 45 },
      { n: "Dijon mustard", g: 12 },
      { n: "Butter", g: 8 },
    ],
  },
  {
    name: "Gammon steak with egg and chips",
    mealType: "dinner",
    prepMinutes: 35,
    keepsDays: 2,
    method: "1. Roast potato chips in oil 30 min at 210C.\n2. Griddle the gammon.\n3. Fry the egg, serve with peas.",
    lines: [
      { n: "Gammon steak", g: 170, scale: [120, 240] },
      { n: "Potatoes", g: 240, scale: [150, 360] },
      { n: "Eggs", g: 58 },
      { n: "Frozen peas", g: 70 },
      { n: "Olive oil", g: 10 },
    ],
  },
  {
    name: "Chicken sausage and butter bean casserole",
    mealType: "dinner",
    prepMinutes: 30,
    batchFriendly: true,
    leftoversFreeze: true,
    keepsDays: 4,
    method: "1. Brown the sausages, slice.\n2. Soften onion, add tomatoes and beans, simmer 20 min.\n3. Wilt kale through, serve with sourdough.",
    lines: [
      { n: "Chicken sausages", g: 180, scale: [120, 250] },
      { n: "Butter beans", g: 150, scale: [100, 220] },
      { n: "Chopped tomatoes", g: 150 },
      { n: "Sourdough bread", g: 40, scale: [0, 90] },
      { n: "Kale", g: 60 },
      { n: "Onion", g: 50 },
      { n: "Olive oil", g: 8 },
    ],
  },
  {
    name: "Pork and fennel pasta",
    mealType: "dinner",
    prepMinutes: 28,
    batchFriendly: true,
    keepsDays: 3,
    method: "1. Brown the pork hard with chilli flakes.\n2. Add sliced fennel, soften.\n3. Add passata, simmer 15 min, toss with pasta and parmesan.",
    lines: [
      { n: "Pork mince (10% fat)", g: 160, scale: [110, 230] },
      { n: "Wholewheat pasta", g: 70, scale: [45, 110], note: "dry weight" },
      { n: "Fennel", g: 80 },
      { n: "Passata", g: 120 },
      { n: "Parmesan", g: 15 },
      { n: "Chilli flakes", g: 1 },
    ],
  },
  {
    name: "Pork and pineapple skewers",
    mealType: "dinner",
    prepMinutes: 28,
    keepsDays: 2,
    method: "1. Thread pork, pineapple and pepper onto skewers.\n2. Grill 12 min, turning, brushing with soy.\n3. Serve on rice.",
    lines: [
      { n: "Pork loin steak", g: 185, scale: [130, 260] },
      { n: "Basmati rice", g: 65, scale: [40, 100], note: "dry weight" },
      { n: "Pineapple", g: 100 },
      { n: "Red pepper", g: 70 },
      { n: "Soy sauce", g: 10 },
      { n: "Sesame oil", g: 6 },
    ],
  },
  {
    name: "Lamb kofta with flatbread",
    mealType: "dinner",
    prepMinutes: 30,
    batchFriendly: true,
    leftoversFreeze: true,
    keepsDays: 3,
    method: "1. Mix lamb with cumin, shape onto skewers, grill hard.\n2. Grate cucumber into the yoghurt.\n3. Serve on warm flatbread with onion and feta.",
    lines: [
      { n: "Lamb mince (10% fat)", g: 160, scale: [110, 220] },
      { n: "Flatbread", g: 80, scale: [40, 120] },
      { n: "Feta", g: 25 },
      { n: "Greek yoghurt (0% fat)", g: 60 },
      { n: "Cucumber", g: 50 },
      { n: "Red onion", g: 30 },
      { n: "Cumin", g: 3 },
    ],
  },
  {
    name: "Lamb and chickpea tagine",
    mealType: "dinner",
    prepMinutes: 45,
    batchFriendly: true,
    leftoversFreeze: true,
    keepsDays: 4,
    method: "1. Brown the lamb, set aside.\n2. Soften onion, add ras el hanout, tomatoes and chickpeas.\n3. Return lamb, simmer 40 min. Serve on couscous.",
    lines: [
      { n: "Lamb leg steak", g: 170, scale: [120, 240] },
      { n: "Chickpeas", g: 120, scale: [80, 180] },
      { n: "Couscous", g: 45, scale: [30, 80], note: "dry weight" },
      { n: "Chopped tomatoes", g: 120 },
      { n: "Onion", g: 50 },
      { n: "Olive oil", g: 6 },
      { n: "Ras el hanout", g: 4 },
    ],
  },
  {
    name: "Lamb steaks with minted peas",
    mealType: "dinner",
    prepMinutes: 28,
    keepsDays: 2,
    method: "1. Boil the new potatoes.\n2. Griddle the lamb 4 min a side, rest.\n3. Crush the peas with butter and parsley.",
    lines: [
      { n: "Lamb leg steak", g: 180, scale: [120, 250] },
      { n: "New potatoes", g: 250, scale: [160, 380] },
      { n: "Frozen peas", g: 120 },
      { n: "Butter", g: 8 },
      { n: "Fresh parsley", g: 5 },
    ],
  },
  {
    name: "Lamb keema with rice",
    mealType: "dinner",
    prepMinutes: 35,
    batchFriendly: true,
    leftoversFreeze: true,
    keepsDays: 4,
    method: "1. Brown the lamb hard, drain the fat.\n2. Add onion, garam masala and tomatoes, simmer 20 min.\n3. Stir peas in at the end, serve on rice with yoghurt.",
    lines: [
      { n: "Lamb mince (10% fat)", g: 160, scale: [110, 220] },
      { n: "Basmati rice", g: 60, scale: [40, 95], note: "dry weight" },
      { n: "Greek yoghurt (0% fat)", g: 60 },
      { n: "Frozen peas", g: 80 },
      { n: "Chopped tomatoes", g: 120 },
      { n: "Onion", g: 50 },
      { n: "Garam masala", g: 5 },
    ],
  },
  {
    name: "Lamb and aubergine bake",
    mealType: "dinner",
    prepMinutes: 50,
    batchFriendly: true,
    leftoversFreeze: true,
    keepsDays: 4,
    method: "1. Griddle aubergine slices.\n2. Brown lamb, add passata and cinnamon, simmer 20 min.\n3. Layer, top with yoghurt beaten with egg and parmesan, bake 30 min.",
    lines: [
      { n: "Lamb mince (10% fat)", g: 150, scale: [100, 210] },
      { n: "Aubergine", g: 200 },
      { n: "Passata", g: 150 },
      { n: "Greek yoghurt (0% fat)", g: 100 },
      { n: "Eggs", g: 58 },
      { n: "Parmesan", g: 20 },
      { n: "Cinnamon", g: 1 },
    ],
  },
  {
    name: "Lamb, tomato and orzo bake",
    mealType: "dinner",
    prepMinutes: 40,
    batchFriendly: true,
    keepsDays: 3,
    method: "1. Brown the lamb with onion and oregano.\n2. Add tomatoes and orzo with a mug of stock.\n3. Bake 25 min, crumble feta over.",
    lines: [
      { n: "Lamb mince (10% fat)", g: 150, scale: [100, 210] },
      { n: "Orzo", g: 55, scale: [35, 90], note: "dry weight" },
      { n: "Feta", g: 50 },
      { n: "Chopped tomatoes", g: 150 },
      { n: "Onion", g: 50 },
      { n: "Dried oregano", g: 2 },
    ],
  },
  {
    name: "Chorizo and king prawn rice",
    mealType: "dinner",
    prepMinutes: 28,
    batchFriendly: true,
    keepsDays: 2,
    method: "1. Render the chorizo, fry pepper in its oil.\n2. Stir in rice and paprika, add stock, cook 18 min.\n3. Prawns and peas in for the last 4 min.",
    lines: [
      { n: "King prawns", g: 180, scale: [120, 250] },
      { n: "Chorizo", g: 55, scale: [35, 80] },
      { n: "Basmati rice", g: 70, scale: [45, 105], note: "dry weight" },
      { n: "Red pepper", g: 70 },
      { n: "Frozen peas", g: 60 },
      { n: "Smoked paprika", g: 3 },
    ],
  },
  {
    name: "Steak and garlic prawns with new potatoes",
    mealType: "dinner",
    prepMinutes: 30,
    keepsDays: 2,
    method: "1. Boil and crush the new potatoes.\n2. Sear the steak, rest.\n3. Fry prawns in garlic butter, spoon over. Griddle the asparagus.",
    lines: [
      { n: "Beef rump steak", g: 150, scale: [100, 220] },
      { n: "King prawns", g: 120, scale: [80, 180] },
      { n: "New potatoes", g: 220, scale: [140, 330] },
      { n: "Asparagus", g: 90 },
      { n: "Butter", g: 10 },
      { n: "Garlic", g: 8 },
    ],
  },
  {
    name: "Chicken and prawn jambalaya",
    mealType: "dinner",
    prepMinutes: 35,
    batchFriendly: true,
    keepsDays: 3,
    method: "1. Render chorizo, brown the chicken.\n2. Soften onion, celery and pepper, stir in rice and stock.\n3. Cook 18 min, prawns in for the last 4.",
    lines: [
      { n: "Chicken thigh (boneless)", g: 130, scale: [90, 190] },
      { n: "King prawns", g: 120, scale: [80, 180] },
      { n: "Chorizo", g: 30, scale: [20, 50] },
      { n: "Basmati rice", g: 70, scale: [45, 105], note: "dry weight" },
      { n: "Red pepper", g: 70 },
      { n: "Celery", g: 50 },
      { n: "Onion", g: 50 },
    ],
  },
  {
    name: "Bacon-wrapped cod with crushed potatoes",
    mealType: "dinner",
    prepMinutes: 30,
    keepsDays: 2,
    method: "1. Wrap each cod loin in bacon, roast 16 min at 200C.\n2. Boil and crush the new potatoes with oil.\n3. Steam the tenderstem, finish with lemon.",
    lines: [
      { n: "Cod fillet", g: 200, scale: [140, 270] },
      { n: "Bacon medallions", g: 50, scale: [30, 80] },
      { n: "New potatoes", g: 250, scale: [160, 380] },
      { n: "Tenderstem broccoli", g: 100 },
      { n: "Olive oil", g: 12 },
      { n: "Lemon", g: 15 },
    ],
  },
  {
    name: "Chorizo, cod and butter bean stew",
    mealType: "dinner",
    prepMinutes: 30,
    batchFriendly: true,
    keepsDays: 2,
    method: "1. Render the chorizo, soften the onion in its oil.\n2. Add tomatoes and butter beans, simmer 15 min.\n3. Lay the cod on top, cover, cook 8 min. Wilt spinach through.",
    lines: [
      { n: "Cod fillet", g: 180, scale: [120, 250] },
      { n: "Chorizo", g: 50, scale: [30, 75] },
      { n: "Butter beans", g: 150, scale: [100, 220] },
      { n: "Chopped tomatoes", g: 150 },
      { n: "Spinach", g: 60 },
      { n: "Onion", g: 50 },
      { n: "Olive oil", g: 8 },
    ],
  },
  {
    name: "Duck breast with orange and greens",
    mealType: "dinner",
    prepMinutes: 35,
    keepsDays: 2,
    method: "1. Score the duck, start skin-down in a cold pan, render 8 min.\n2. Finish in the oven 8 min, rest.\n3. Deglaze with orange juice, honey and soy. Serve with potatoes and tenderstem.",
    lines: [
      { n: "Duck breast", g: 190, scale: [130, 260] },
      { n: "New potatoes", g: 220, scale: [140, 330] },
      { n: "Tenderstem broccoli", g: 100 },
      { n: "Orange", g: 80 },
      { n: "Honey", g: 10 },
      { n: "Soy sauce", g: 10 },
    ],
  },
  {
    name: "Duck and noodle stir-fry",
    mealType: "dinner",
    prepMinutes: 25,
    keepsDays: 2,
    method: "1. Render and slice the duck.\n2. Stir-fry pak choi in sesame oil.\n3. Toss with noodles, hoisin and spring onion.",
    lines: [
      { n: "Duck breast", g: 180, scale: [120, 250] },
      { n: "Egg noodles", g: 70, scale: [45, 110], note: "dry weight" },
      { n: "Hoisin sauce", g: 25 },
      { n: "Pak choi", g: 100 },
      { n: "Spring onion", g: 20 },
      { n: "Sesame oil", g: 6 },
    ],
  },
  {
    name: "Jerk chicken with rice and peas",
    mealType: "dinner",
    prepMinutes: 40,
    batchFriendly: true,
    keepsDays: 3,
    method: "1. Rub the drumsticks in jerk seasoning, roast 35 min at 200C.\n2. Cook rice with coconut milk and kidney beans.\n3. Scatter spring onion.",
    lines: [
      { n: "Chicken drumsticks", g: 220, scale: [150, 300] },
      { n: "Basmati rice", g: 55, scale: [35, 90], note: "dry weight" },
      { n: "Kidney beans", g: 80, scale: [50, 130] },
      { n: "Coconut milk", g: 40 },
      { n: "Jerk seasoning", g: 8 },
      { n: "Spring onion", g: 20 },
    ],
  },
  {
    name: "Bacon, pea and parmesan rice",
    mealType: "dinner",
    prepMinutes: 30,
    batchFriendly: true,
    keepsDays: 2,
    method: "1. Crisp the bacon, brown the chicken in the fat.\n2. Soften onion, stir in rice, add stock a ladle at a time.\n3. Peas and parmesan in at the end.",
    lines: [
      { n: "Chicken breast", g: 100, scale: [60, 150] },
      { n: "Bacon medallions", g: 90, scale: [50, 130] },
      { n: "Basmati rice", g: 70, scale: [45, 105], note: "dry weight" },
      { n: "Frozen peas", g: 100 },
      { n: "Parmesan", g: 25, scale: [12, 35] },
      { n: "Onion", g: 50 },
      { n: "Stock cubes", g: 6 },
    ],
  },
];
